import ThemeRegistry from "./themeRegistry"
import { NextAuthProvider } from "./provider"
import Navbar from "@/app/components/Navbar"

export const metadata = {
  title: 'pondok kos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }, NextResponse) {

  return (
    <html lang="en">
      <body>
        {/* <NextAuthProvider> */}
        <ThemeRegistry options={{ key: 'mui' }}>
          <Navbar />
          {children}
        </ThemeRegistry>
        {/* </NextAuthProvider> */}
      </body>
    </html>
  )
}
