import ThemeRegistry from "./themeRegistry"
import { NextAuthProvider } from "./provider"

export const metadata = {
  title: 'pondok kos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <NextAuthProvider> */}
          <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
        {/* </NextAuthProvider> */}
      </body>
    </html>
  )
}
