import ThemeRegistry from "./themeRegistry"
// import favicon from './'

export const metadata = {
  title: 'pondok kos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
      </body>
    </html>
  )
}
